CREATE TABLE IF NOT EXISTS mydb.Roles(
    RoleID INT auto_increment NOT NULL,
	role varchar(255) NOT NULL,
    CONSTRAINT Role_PK PRIMARY KEY (RoleID)
);
CREATE TABLE IF NOT EXISTS mydb.Userinfo(
    UserinfoID INT auto_increment NOT NULL,
	firstname varchar(255) NOT NULL,
	lastname varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	birthday date NOT NULL,
    phonenumber varchar(255) NOT NULL,
	address varchar(255) NOT NULL,
    zipcode varchar(255) NOT NULL,
	city varchar(255) NOT NULL,
   	CONSTRAINT Users_PK PRIMARY KEY (UserinfoID)
);
CREATE TABLE IF NOT EXISTS mydb.Images (
	ImageID INT auto_increment NOT NULL,
	imagepath varchar(255) NOT NULL,
	imagename varchar(255) NOT NULL,
	CONSTRAINT Images_PK PRIMARY KEY (ImageID)
);
CREATE TABLE IF NOT EXISTS mydb.Gallery (
	GalleryID INT auto_increment NOT NULL,
	CONSTRAINT Gallery_PK PRIMARY KEY (GalleryID)
);
CREATE TABLE IF NOT EXISTS mydb.Gallery_Images (
	Gallery_ImageID INT auto_increment NOT NULL,
	GalleryID INT NOT NULL,
	ImageID INT NOT NULL,
	CONSTRAINT Gallery_Images_PK PRIMARY KEY (Gallery_ImageID),
	CONSTRAINT Gallery_Images_Gallery_FK FOREIGN KEY (GalleryID) REFERENCES mydb.Gallery(GalleryID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT Gallery_Images_Images_FK FOREIGN KEY (ImageID) REFERENCES mydb.Images(ImageID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS mydb.Pages (
	PageID INT auto_increment NOT NULL,
	title varchar(255) DEFAULT "This is the title" NOT NULL,
	subtext TEXT NOT NULL,
	price DOUBLE DEFAULT 0.00 NOT NULL,
	GalleryID INT NOT NULL,
	ImageID INT NOT NULL,
	CONSTRAINT Pages_PK PRIMARY KEY (PageID),
	CONSTRAINT Pages_Gallery_FK FOREIGN KEY (GalleryID) REFERENCES mydb.Gallery(GalleryID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT Pages_Images_FK FOREIGN KEY (ImageID) REFERENCES mydb.Images(ImageID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS mydb.Users(
    UserID INT auto_increment NOT NULL,
	username varchar(255) NOT NULL,
	password varchar(255) NOT NULL,
	UserinfoID INT NOT NULL,
	RoleID INT NOT NULL,
	CONSTRAINT Users_PK PRIMARY KEY (UserID),
	CONSTRAINT Users_Userinfo_FK FOREIGN KEY (UserinfoID) REFERENCES mydb.Userinfo(UserinfoID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT Users_Roles_FK FOREIGN KEY (RoleID) REFERENCES mydb.Roles(RoleID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS mydb.Bnbs (
	BnbID INT auto_increment NOT NULL,
	rooms INT NOT NULL,
	beds INT NOT NULL,
	available BOOL NOT NULL,
	PageID INT NOT NULL,
	UserID INT NOT NULL,
	CONSTRAINT Bnbs_PK PRIMARY KEY (BnbID),
	CONSTRAINT Bnbs_Users_FK FOREIGN KEY (UserID) REFERENCES mydb.Users(UserID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT Bnbs_Pages_FK FOREIGN KEY (PageID) REFERENCES mydb.Pages(PageID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS mydb.Bookings (
	BookingID INT auto_increment NOT NULL,
	checkin DATETIME NOT NULL,
	checkout DATETIME NOT NULL,
	BnbID INT NOT NULL,
	CONSTRAINT Bookings_PK PRIMARY KEY (BookingID),
	CONSTRAINT Bookings_Bnbs_FK FOREIGN KEY (BnbID) REFERENCES mydb.Bnbs(BnbID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS mydb.Bookings_Users (
	Booking_UserID INT NOT NULL,
	BookingID INT NOT NULL,
	UserID INT NOT NULL,
	CONSTRAINT Bookings_Users_PK PRIMARY KEY (Booking_UserID),
	CONSTRAINT Bookings_Users_Bookings_FK FOREIGN KEY (BookingID) REFERENCES mydb.Bookings(BookingID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT Bookings_Users_Users_FK FOREIGN KEY (UserID) REFERENCES mydb.Users(UserID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS mydb.Guests(
    GuestID INT auto_increment NOT NULL,
	UserinfoID INT NOT NULL,
	CONSTRAINT Guests_PK PRIMARY KEY (GuestID),
	CONSTRAINT Guests_Userinfo_FK FOREIGN KEY (UserinfoID) REFERENCES mydb.Userinfo(UserinfoID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS mydb.Bookings_Guests (
	Booking_GuestID INT auto_increment NOT NULL,
	BookingID INT NOT NULL,
	GuestID INT NOT NULL,
	CONSTRAINT Bookings_Guests_PK PRIMARY KEY (Booking_GuestID),
	CONSTRAINT Bookings_Guests_Bookings_FK FOREIGN KEY (BookingID) REFERENCES mydb.Bookings(BookingID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT Bookings_Guests_Guests_FK FOREIGN KEY (GuestID) REFERENCES mydb.Guests(GuestID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS mydb.Reviews (
	ReviewID INT auto_increment NOT NULL,
	rating DOUBLE NOT NULL,
	title varchar(255) NOT NULL,
	comment TEXT NOT NULL,
	`time` DATETIME NOT NULL,
	UserID INT NOT NULL,
	BnbID INT NOT NULL,
	CONSTRAINT Reviews_PK PRIMARY KEY (ReviewID),
	CONSTRAINT Reviews_Bnbs_FK FOREIGN KEY (BnbID) REFERENCES mydb.Bnbs(BnbID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT Reviews_Users_FK FOREIGN KEY (UserID) REFERENCES mydb.Users(UserID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS mydb.Users_Image (
	User_ImageID INT auto_increment NOT NULL,
	UserID INT NOT NULL,
	ImageID INT NOT NULL,
	CONSTRAINT Users_Image_PK PRIMARY KEY (User_ImageID),
	CONSTRAINT Users_Image_Images_FK FOREIGN KEY (ImageID) REFERENCES mydb.Images(ImageID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT Users_Image_Users_FK FOREIGN KEY (UserID) REFERENCES mydb.Users(UserID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS mydb.User_Guests (
	User_GuestID INT auto_increment NOT NULL,
	UserID INT NOT NULL,
	GuestID INT NOT NULL,
	CONSTRAINT User_Guests_PK PRIMARY KEY (User_GuestID),
	CONSTRAINT User_Guests_Users_FK FOREIGN KEY (UserID) REFERENCES mydb.Users(UserID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT User_Guests_Guests_FK FOREIGN KEY (GuestID) REFERENCES mydb.Guests(GuestID) ON DELETE CASCADE ON UPDATE CASCADE
)